# Generated by Django 3.1.4 on 2021-02-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20210225_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='userRate',
            field=models.CharField(choices=[('0', 'None'), ('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five'), ('6', 'Six'), ('7', 'Seven'), ('8', 'Eight'), ('9', 'Nine'), ('10', 'Ten')], default='0', max_length=255),
        ),
    ]
